// example 1 -- here param is a boolean
const mainFunc = value => {
    if (value == true) {
        console.log("this is true");
    } else {
        console.log("this is false");
    }
};

mainFunc(false);

/*
a func argument could be anything. 
string/number/boolean/ object/array/null/undef/another func
*/

const mainFunc2 = value => {
    if (typeof value == "object") {
        console.log("hello, " + value.name);
    } else if (typeof value == "undefined") {
        console.log("hello");
    } else {
        console.log("hello, " + value);
    }
};

mainFunc2("vikas");
mainFunc2({ name: "vikram" });
mainFunc2();

/**/

const func3 = param => {
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....
    //.....

    param();
};

const func4 = () => {
    console.log("this is completed");
};

func3(func4);

// whenever you pass a func as an param/argument to another func,
// it is called a callback func
